import { Infographic, Article, ContentFile } from '../types';

// This is a MOCK implementation. In a real scenario with Decap CMS,
// you would fetch .json or .md files from the paths specified in config.yml
// (e.g., from /content/infographics/ or /content/articles/)
// These files are generated by Decap CMS when content is saved.

const MOCK_INFOGRAPHICS_DATA: Infographic[] = [
  { id: 'ข้าวหอมมะลิ', title: 'เทคนิคการปลูกข้าวหอมมะลิให้ได้ผลผลิตสูง', image: '/sample-images/rice.jpg', summary: 'เรียนรู้ขั้นตอนการเตรียมดิน การเลือกพันธุ์ และการดูแลข้าวหอมมะลิอย่างถูกวิธีเพื่อให้ได้ข้าวคุณภาพดีและปริมาณมาก', category: 'ข้าว', tags: ['ข้าวหอมมะลิ', 'การปลูกข้าว'], published_date: '2024-07-15T10:00:00Z', contentPath: 'infographics/ข้าวหอมมะลิ.json' },
  { id: 'มะม่วงน้ำดอกไม้', title: 'การดูแลมะม่วงน้ำดอกไม้ให้ติดผลดก', image: '/sample-images/mango.jpg', summary: 'เคล็ดลับการตัดแต่งกิ่ง การให้ปุ๋ย และการป้องกันโรคสำหรับมะม่วงน้ำดอกไม้ เพื่อให้ได้ผลผลิตที่สมบูรณ์', category: 'ผลไม้', tags: ['มะม่วง', 'การดูแลผลไม้'], published_date: '2024-07-10T14:30:00Z', contentPath: 'infographics/มะม่วงน้ำดอกไม้.json' },
  { id: 'ผักปลอดสารพิษ', title: 'เริ่มต้นปลูกผักปลอดสารพิษในครัวเรือน', image: '/sample-images/vegetables.jpg', summary: 'คู่มือสำหรับผู้เริ่มต้นที่สนใจปลูกผักไว้ทานเอง ปลอดภัย ไร้สารเคมีตกค้าง ดีต่อสุขภาพ', category: 'พืชผัก', tags: ['เกษตรอินทรีย์', 'ผักสวนครัว'], published_date: '2024-07-05T09:00:00Z', contentPath: 'infographics/ผักปลอดสารพิษ.json' },
  { id: 'โดรนเกษตร', title: 'การใช้โดรนเพื่อการเกษตรสมัยใหม่', image: '/sample-images/drone.jpg', summary: 'สำรวจประโยชน์ของเทคโนโลยีโดรนในการพ่นปุ๋ย ยา และการสำรวจแปลงเกษตร ช่วยเพิ่มประสิทธิภาพและลดต้นทุน', category: 'เทคโนโลยีการเกษตร', tags: ['โดรน', 'เกษตรแม่นยำ'], published_date: '2024-06-28T11:00:00Z', contentPath: 'infographics/โดรนเกษตร.json' },
];

// Create dummy image files in public/sample-images for mock data
// For example: public/sample-images/rice.jpg, mango.jpg, vegetables.jpg, drone.jpg
// If using picsum.photos, ensure internet access during development.
// Using local placeholders is better for offline dev.

const MOCK_ARTICLES_DATA: Article[] = [
  { id: 'smart-farming', title: 'Smart Farming: อนาคตเกษตรกรรมไทย', excerpt: 'การนำเทคโนโลยี IoT, AI และ Big Data มาประยุกต์ใช้ในการทำเกษตร...', content: '## Smart Farming คืออะไร...\n\nเนื้อหาบทความเต็ม...', category: 'เทคโนโลยีการเกษตร', tags: ['smart farming', 'IoT'], published_date: '2024-07-12T00:00:00Z', contentPath: 'articles/smart-farming.md' },
  { id: 'soil-improvement', title: 'เทคนิคการปรับปรุงดินเพื่อผลผลิตที่ดีขึ้น', excerpt: 'ดินดีเป็นหัวใจสำคัญของการเพาะปลูก เรียนรู้วิธีการปรับปรุงโครงสร้างดิน...', content: '## ความสำคัญของดิน...\n\nเนื้อหาบทความเต็ม...', category: 'พืชผัก', tags: ['ดิน', 'ปุ๋ยอินทรีย์'], published_date: '2024-07-08T00:00:00Z', contentPath: 'articles/soil-improvement.md' },
];

async function fetchContentList(type: 'infographics' | 'articles'): Promise<string[]> {
    if (type === 'infographics') {
        return MOCK_INFOGRAPHICS_DATA.map(item => item.contentPath); // Use full path
    }
    if (type === 'articles') {
        return MOCK_ARTICLES_DATA.map(item => item.contentPath); // Use full path
    }
    return [];
}

async function fetchContentFile<T>(filePath: string): Promise<ContentFile<T> | null> {
    console.log(`Simulating fetch for: /content/${filePath}`); // filePath is now like 'infographics/filename.json'
    await new Promise(resolve => setTimeout(resolve, 100));

    const idFromPath = filePath.substring(filePath.lastIndexOf('/') + 1).replace(/\.(json|md)$/, '');

    if (filePath.startsWith('infographics/')) {
        const data = MOCK_INFOGRAPHICS_DATA.find(item => item.id === idFromPath);
        if (data) return data as unknown as ContentFile<T>;
    } else if (filePath.startsWith('articles/')) {
        const data = MOCK_ARTICLES_DATA.find(item => item.id === idFromPath);
         if (data) return data as unknown as ContentFile<T>;
    }
    return null;
}

export const getInfographics = async (): Promise<Infographic[]> => {
  const fileList = await fetchContentList('infographics');
  const infographics: Infographic[] = [];

  for (const filePath of fileList) {
    const data = await fetchContentFile<Infographic>(filePath);
    if (data) {
      const id = filePath.substring(filePath.lastIndexOf('/') + 1).replace('.json', '');
      infographics.push({
        id: id,
        title: data.title,
        image: data.image || `/sample-images/default.jpg`, 
        summary: data.summary || 'ไม่มีข้อมูลสรุป',
        category: data.category,
        tags: data.tags,
        published_date: data.published_date,
        full_text_from_ocr: data.full_text_from_ocr,
        contentPath: filePath
      });
    }
  }
  return infographics.sort((a, b) => new Date(b.published_date).getTime() - new Date(a.published_date).getTime());
};

export const getInfographicById = async (contentPath: string): Promise<Infographic | null> => {
  const data = await fetchContentFile<Infographic>(contentPath);
  if (data) {
    const id = contentPath.substring(contentPath.lastIndexOf('/') + 1).replace('.json', '');
    return {
      id: id,
      title: data.title,
      image: data.image || `/sample-images/default.jpg`,
      summary: data.summary || 'ไม่มีข้อมูลสรุป',
      category: data.category,
      tags: data.tags,
      published_date: data.published_date,
      full_text_from_ocr: data.full_text_from_ocr,
      contentPath: contentPath
    };
  }
  return null;
};

export const getArticles = async (): Promise<Article[]> => {
  const fileList = await fetchContentList('articles');
  const articles: Article[] = [];

  for (const filePath of fileList) {
    const data = await fetchContentFile<Article>(filePath);
    if (data) {
      const id = filePath.substring(filePath.lastIndexOf('/') + 1).replace('.md', '');
      articles.push({
        id: id,
        title: data.title,
        excerpt: data.body ? data.body.substring(0, 150) + '...' : 'ไม่มีเนื้อหาตัวอย่าง',
        content: data.body || '',
        category: data.category,
        tags: data.tags,
        published_date: data.published_date,
        contentPath: filePath
      });
    }
  }
  return articles.sort((a, b) => new Date(b.published_date).getTime() - new Date(a.published_date).getTime());
};

export const getArticleById = async (contentPath: string): Promise<Article | null> => {
  const data = await fetchContentFile<Article>(contentPath);
  if (data) {
     const id = contentPath.substring(contentPath.lastIndexOf('/') + 1).replace('.md', '');
    return {
      id: id,
      title: data.title,
      excerpt: data.body ? data.body.substring(0, 150) + '...' : 'ไม่มีเนื้อหาตัวอย่าง',
      content: data.body || '',
      category: data.category,
      tags: data.tags,
      published_date: data.published_date,
      contentPath: contentPath
    };
  }
  return null;
};
