
import { Infographic, Article, ContentFile } from '../types';

// This is a MOCK implementation. In a real scenario with Decap CMS,
// you would fetch .json or .md files from the paths specified in config.yml
// (e.g., from /content/infographics/ or /content/articles/)
// These files are generated by Decap CMS when content is saved.

const MOCK_INFOGRAPHICS_DATA: Infographic[] = [
  { id: 'ข้าวหอมมะลิ', title: 'เทคนิคการปลูกข้าวหอมมะลิให้ได้ผลผลิตสูง', image: 'https://picsum.photos/seed/rice1/400/300', summary: 'เรียนรู้ขั้นตอนการเตรียมดิน การเลือกพันธุ์ และการดูแลข้าวหอมมะลิอย่างถูกวิธีเพื่อให้ได้ข้าวคุณภาพดีและปริมาณมาก', category: 'ข้าว', tags: ['ข้าวหอมมะลิ', 'การปลูกข้าว'], published_date: '2024-07-15T10:00:00Z', contentPath: 'ข้าวหอมมะลิ.json' },
  { id: 'มะม่วงน้ำดอกไม้', title: 'การดูแลมะม่วงน้ำดอกไม้ให้ติดผลดก', image: 'https://picsum.photos/seed/mango1/400/300', summary: 'เคล็ดลับการตัดแต่งกิ่ง การให้ปุ๋ย และการป้องกันโรคสำหรับมะม่วงน้ำดอกไม้ เพื่อให้ได้ผลผลิตที่สมบูรณ์', category: 'ผลไม้', tags: ['มะม่วง', 'การดูแลผลไม้'], published_date: '2024-07-10T14:30:00Z', contentPath: 'มะม่วงน้ำดอกไม้.json' },
  { id: 'ผักปลอดสารพิษ', title: 'เริ่มต้นปลูกผักปลอดสารพิษในครัวเรือน', image: 'https://picsum.photos/seed/veg1/400/300', summary: 'คู่มือสำหรับผู้เริ่มต้นที่สนใจปลูกผักไว้ทานเอง ปลอดภัย ไร้สารเคมีตกค้าง ดีต่อสุขภาพ', category: 'พืชผัก', tags: ['เกษตรอินทรีย์', 'ผักสวนครัว'], published_date: '2024-07-05T09:00:00Z', contentPath: 'ผักปลอดสารพิษ.json' },
  { id: 'โดรนเกษตร', title: 'การใช้โดรนเพื่อการเกษตรสมัยใหม่', image: 'https://picsum.photos/seed/drone1/400/300', summary: 'สำรวจประโยชน์ของเทคโนโลยีโดรนในการพ่นปุ๋ย ยา และการสำรวจแปลงเกษตร ช่วยเพิ่มประสิทธิภาพและลดต้นทุน', category: 'เทคโนโลยีการเกษตร', tags: ['โดรน', 'เกษตรแม่นยำ'], published_date: '2024-06-28T11:00:00Z', contentPath: 'โดรนเกษตร.json' },
];

const MOCK_ARTICLES_DATA: Article[] = [
  { id: 'smart-farming', title: 'Smart Farming: อนาคตเกษตรกรรมไทย', excerpt: 'การนำเทคโนโลยี IoT, AI และ Big Data มาประยุกต์ใช้ในการทำเกษตร...', content: '## Smart Farming คืออะไร...\n\nเนื้อหาบทความเต็ม...', category: 'เทคโนโลยีการเกษตร', tags: ['smart farming', 'IoT'], published_date: '2024-07-12T00:00:00Z', contentPath: 'smart-farming.md' },
  { id: 'soil-improvement', title: 'เทคนิคการปรับปรุงดินเพื่อผลผลิตที่ดีขึ้น', excerpt: 'ดินดีเป็นหัวใจสำคัญของการเพาะปลูก เรียนรู้วิธีการปรับปรุงโครงสร้างดิน...', content: '## ความสำคัญของดิน...\n\nเนื้อหาบทความเต็ม...', category: 'พืชผัก', tags: ['ดิน', 'ปุ๋ยอินทรีย์'], published_date: '2024-07-08T00:00:00Z', contentPath: 'soil-improvement.md' },
];

// Simulate fetching a list of content files (e.g., .json files for infographics)
async function fetchContentList(type: 'infographics' | 'articles'): Promise<string[]> {
    // In reality, this would list files in a directory, e.g., /content/infographics/
    // For mock, we'll use the IDs from MOCK_DATA as pseudo file names
    if (type === 'infographics') {
        return MOCK_INFOGRAPHICS_DATA.map(item => `${item.id}.json`);
    }
    if (type === 'articles') {
        return MOCK_ARTICLES_DATA.map(item => `${item.id}.md`);
    }
    return [];
}

async function fetchContentFile<T>(filePath: string): Promise<ContentFile<T> | null> {
    console.log(`Simulating fetch for: /content/${filePath}`);
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 300));

    const id = filePath.substring(filePath.lastIndexOf('/') + 1).replace(/\.(json|md)$/, '');

    if (filePath.startsWith('infographics/')) {
        const data = MOCK_INFOGRAPHICS_DATA.find(item => item.id === id);
        if (data) return data as unknown as ContentFile<T>; // Cast to ContentFile<T> for structure
    } else if (filePath.startsWith('articles/')) {
        const data = MOCK_ARTICLES_DATA.find(item => item.id === id);
         if (data) return data as unknown as ContentFile<T>; // Cast to ContentFile<T> for structure
    }
    return null;
}


export const getInfographics = async (): Promise<Infographic[]> => {
  // Simulate fetching all infographic JSON files and parsing them
  // In a real app, this would involve:
  // 1. Fetching a list of files in the 'content/infographics' directory (e.g., using a manifest file or server API if not on static hosting that allows directory listing)
  // 2. Fetching each JSON file and parsing it.
  
  const fileList = await fetchContentList('infographics');
  const infographics: Infographic[] = [];

  for (const fileName of fileList) {
    // Here, T is Infographic for ContentFile<Infographic>
    const data = await fetchContentFile<Infographic>(`infographics/${fileName}`);
    if (data) {
      infographics.push({
        id: fileName.replace('.json', ''), // or extract from data if slug is different
        title: data.title,
        image: data.image || `https://picsum.photos/seed/${fileName}/400/300`, // Fallback for image
        summary: data.summary || 'ไม่มีข้อมูลสรุป', // Fallback for summary
        category: data.category,
        tags: data.tags,
        published_date: data.published_date,
        full_text_from_ocr: data.full_text_from_ocr,
        contentPath: `infographics/${fileName}`
      });
    }
  }
  // Sort by published date, newest first
  return infographics.sort((a, b) => new Date(b.published_date).getTime() - new Date(a.published_date).getTime());
};

export const getInfographicById = async (id: string): Promise<Infographic | null> => {
  // id here is expected to be the contentPath, e.g., "infographics/filename.json"
  // So, fetchContentFile should use T = Infographic implicitly by how data is structured,
  // but ContentFile<Infographic> is more accurate for what `data` will be.
  const data = await fetchContentFile<Infographic>(id);
  if (data) {
    // Explicitly construct the Infographic object to ensure all required fields are met
    // and no extraneous fields (like 'body' from ContentFile) are included.
    return {
      id: id.substring(id.lastIndexOf('/') + 1).replace('.json', ''),
      title: data.title,
      image: data.image || `https://picsum.photos/seed/${id}/800/600`, // Ensure image is string
      summary: data.summary || 'ไม่มีข้อมูลสรุป', // Ensure summary is string
      category: data.category,
      tags: data.tags,
      published_date: data.published_date,
      full_text_from_ocr: data.full_text_from_ocr, // This is optional in Infographic
      contentPath: id // This is optional in Infographic
    };
  }
  return null;
};


export const getArticles = async (): Promise<Article[]> => {
  const fileList = await fetchContentList('articles');
  const articles: Article[] = [];

  for (const fileName of fileList) {
    const data = await fetchContentFile<Article>(`articles/${fileName}`);
    if (data) {
      articles.push({
        id: fileName.replace('.md', ''),
        title: data.title,
        excerpt: data.body ? data.body.substring(0, 150) + '...' : 'ไม่มีเนื้อหาตัวอย่าง',
        content: data.body || '',
        category: data.category,
        tags: data.tags,
        published_date: data.published_date,
        contentPath: `articles/${fileName}`
      });
    }
  }
  return articles.sort((a, b) => new Date(b.published_date).getTime() - new Date(a.published_date).getTime());
};


export const getArticleById = async (id: string): Promise<Article | null> => {
  // id here is expected to be the contentPath, e.g., "articles/filename.md"
  const data = await fetchContentFile<Article>(id);
  if (data) {
    return {
      id: id.substring(id.lastIndexOf('/') + 1).replace('.md', ''),
      title: data.title, // Added title, was missing
      excerpt: data.body ? data.body.substring(0, 150) + '...' : 'ไม่มีเนื้อหาตัวอย่าง',
      content: data.body || '',
      category: data.category, // Added category
      tags: data.tags, // Added tags
      published_date: data.published_date, // Added published_date
      contentPath: id
      // Note: Original spread `...data` was removed. Ensure all needed fields from Article are mapped.
      // Article interface includes: id, title, excerpt, content, category, tags, published_date, contentPath?
    };
  }
  return null;
};
